name: generateJsDoc
on:
  push:
    branches: [main]

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.15.1"

      - run: npm install -g jsdoc

      - name: Generate JSDoc
        run: |
          cd Proyect-JsonServerDocker/client
          rm -rf docs/*
          jsdoc -r ./src/js -d ./docs

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Proyect-JsonServerDocker/client/docs
          git commit -m "Update JSDoc"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
